### PR TITLE
Change Dockerfile extensions to avoid breaking semgrep-app

### PR DESCRIPTION
**Pull request by mjambon**

### CODE REVIEW

**Review by aryx — APPROVED** [review]
How this change will fix a broken semgrep-app?
And what was broken in the first place?
You've mostly changed the order of the entries in the exts field, so I don't see how this can change anything.

**Comment by mjambon** [comment]
@aryx They were using `Dockerfile` (no period) as an "extension" when creating some temporary file but some other part of their code was assuming that every file had a proper extension with a period - or something like this.

The fix here is to specify the `example_ext` field which the app should use if it's present.

**Comment by aryx** [comment]
Ok. Maybe worth mentioning in the readme that explains the schema.

**Review by underyx — APPROVED** [review]
Looks ok; though I was already comfortable with the fix we had in the app. I'm comfortable with that because if we ever find a file format that legitimately has no common extension in the `.lowercase` format, the we now has a simple naming scheme for how we can add example files for that.

**Pull request merged**
